### ISSUE TITLE
How to configure max line length in formatter

### ISSUE THREAD

**Issue by sebthom** [eclipse/dartboard#173]
The source code formatter (Ctrl+Shift+F) currently inserts line breaks into lines longer than 80 characters.

How can the line length be increased/configured?

**Comment by jonas-jonas** [comment]
Thi sis somewhat a limitation of the Eclipse platform (see https://github.com/eclipse/dartboard/issues/5).

> How can the line length be increased/configured?

This can't be configured manually, as the Dart formatter is **very** opinionated and doesn't allow for much (if any) configuration from the user.

As for synchronizing the Dart formatter settings with Eclipse: It is currently not possible to set these formatting settings (indentation style for example) just for Dart files.

A workaround for you is, to set the Dart formatter settings manually in the settings for all Editors.

I have been reluctant to set these by default, because users might want other settings for different files types.

**Comment by sebthom** [comment]
I don't know how dartboard invokes the dart formatter, but on the command line you can do something like "dartfmt --line-length 120" I think. So maybe that line length could be configured globally in the dartboard settings and/or per project.

**Comment by jonas-jonas** [comment]
The formatter is invoked by the Dart SDK, specifically the Dart analysis server. That's why we don't have much freedom here to configure. 

Again, the solution here should be to add the option in the Eclipse Platform to configure these settings on a file type basis, which is a rather complex undertaking. That's why there is no progress on this yet.
