### ISSUE TITLE
NPE in Run as Dart Program

### ISSUE THREAD

**Issue by PPazderski** [eclipse/dartboard#94]
To reproduce create a Dart Project with a file in it. Right click on the file -> Run as -> Run as Dart Program. Produce following stacktrace (truncated):

> java.lang.NullPointerException
>	at org.eclipse.dartboard.launch.LaunchShortcut.launch(LaunchShortcut.java:62)
>	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchShortcutExtension.launch(LaunchShortcutExtension.java:431)
>	at org.eclipse.debug.internal.ui.actions.LaunchShortcutAction.runInternal(LaunchShortcutAction.java:88)
>	at org.eclipse.debug.internal.ui.actions.LaunchShortcutAction.runWithEvent(LaunchShortcutAction.java:135)

**Comment by lak-proddev** [comment]
@jonas-jonas     
 **_Run as -> Run as Dart Program._** should enable only on a project  right?

**Comment by jonas-jonas** [comment]
> Run as -> Run as Dart Program. should enable only on a project right?

Ideally the enabler would recognize that a file belongs to a project and run the config for the project. This would enable a user to use the Run as -> Run as Dart Program on any file and the launch config manager would decide which project's config to run. I'm not sure if this common but feels like a good idea, since developers wouldn't have to switch context (by searching for the toplevel project).

So yeah, the entry should show only on files/directories that are contained in a Dart project or projects that are Dart project (see property tester for this).
